fireblocks/fireblocks-sdk-py

- fireblocks_sdk/sdk.py
- update_vault_account
- set_confirmation_threshold_for_txid
- set_confirmation_threshold_for_txhash
> V1.5.6 : Update vaultAccount + setConfirmationThreshold 

- fireblocks_sdk/sdk.py
- fireblocks_sdk/sdk_token_provider.py
- setup.py
- get_public_key_info
- get_public_key_info_for_vault_account
> Get Public Key Info

- fireblocks_sdk/sdk.py
- get_gas_station_info
- set_gas_station_configuration
> V1.5.8: gas_station

- fireblocks_sdk/sdk.py
- drop_transaction
- get_max_spendable_amount
> Drop transaction & Max spendable amount

- fireblocks_sdk/sdk.py
- create_transaction
- create_raw_transaction
> Update transaction creation

- fireblocks_sdk/sdk.py
fixing https://github.com/fireblocks/fireblocks-sdk-py/issues/22
> Add auto fuel param in create_vault_account

- fireblocks_sdk/sdk.py
fixes https://github.com/fireblocks/fireblocks-sdk-py/issues/21
> Idempotency Key

- fireblocks_sdk/sdk.py
> Get users method

- fireblocks_sdk/sdk_token_provider.py
- setup.py
fix https://github.com/fireblocks/fireblocks-sdk-py/issues/27
> upgrade pyjwt version

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
resolves https://github.com/fireblocks/fireblocks-sdk-py/issues/41
> add timeout ability in fireblocks sdk

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
resolves https://github.com/fireblocks/fireblocks-sdk-py/issues/37
now exception object will contain `error_code` argument which contains the error code if it's present
> add error_code to fireblocks-api-exception

- fireblocks_sdk/sdk.py
Added the following endpoints:
- Allocation of funds to a private ledger
- Deallocation of funds from a private ledger
- Get an off-exchange accounts
- Get an off-exchange accounts by off-exchange id
> Feat: Added new off-exchange endpoints

- fireblocks_sdk/sdk.py
resolves https://github.com/fireblocks/fireblocks-sdk-py/issues/60
> Handle JSONDecodeError

- fireblocks_sdk/sdk.py
Expose the existing priority fee parameter of the developer api
> Expose the priority fee parameter

- fireblocks_sdk/sdk.py
Fixed assignment of idempotency key. Changed ':' to '='
> Fixed Idempotency Key Header

- fireblocks_sdk/sdk.py
added get_max_bip44_index_used function
> added get_max_bip44_index_used

- fireblocks_sdk/sdk.py
This pr adds collection and token name sorting to get NFTs tokens and NFTS token ownership.
> Add NFT collection and token name sorting

- fireblocks_sdk/sdk.py
Adds new route for set networkId name
> add set networkId name route

- fireblocks_sdk/sdk.py
- Add blockchainDescriptor as a sorting option to getOwnedNFTs and getNFTs methods
- Add search option to getOwnedNFTs
- Add collection ownership api
> Update fireblocks sdk py

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
Add get_audit_logs method
https://docs.fireblocks.com/api/swagger-ui/#/Audit%20Logs/get_audits
> Get audit logs

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
Add new list owned (NFT) assets endpoint
Add new status filter to list owned collections
> Add list owned assets endpoint 

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
Adding TAP (Transaction Authorization Policy) endpoints in BETA mode( being FF):
get active policy
get draft
update draft
publish draft
publish policy rules
> TAP Endpoints

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
Add smart transfer endpoints to SDK
> add smart transfer endpoints

- fireblocks_sdk/sdk.py
Reverts fireblocks/fireblocks-sdk-py#130
Missing typing imports
> Revert "Add users_groups endpoints"

- fireblocks_sdk/sdk.py
added a method that returns a paginated response of the addresses for a given vault account and asset
> Add get paginated addresses method

- fireblocks_sdk/sdk.py
Safe encode external tx id value in GET /v1/transactions/external_tx_id/{external_tx_id}
> safe encode external_tx_id 

- fireblocks_sdk/tokenization_api_types.py
Remove not-in-specs object fields from BurnCollectionTokenRequest object
> removed unnecessary field from BurnCollectionTokenRequest

- fireblocks_sdk/sdk.py
Fixes the following issues
abi and name missing in add abi endpoint
fixes routes
> Fix abi issue

- fireblocks_sdk/ncw_sdk.py
- fireblocks_sdk/sdk.py
Added two new functions for NCW GetPublicKey
> GetPublicKeyInfo for NCW

- fireblocks_sdk/api_types.py
This pr changes `scope` property for assets api to uppercase (Global => GLOBAL).
> feat: change scope property to upper-case

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
This pr updates the blockchain and asset listing endpoints to GA.
> feat: blockchains and assets endpoints GA

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
This pr fixes the blockchain and asset listing filters.
> fix: blockchain and asset listing filters

- fireblocks_sdk/api_types.py
- fireblocks_sdk/sdk.py
This pr adds ids filter to assets and blockchains listing endpoints.
> Add ids filter for assets and blockchains listing endpoints
